fix pipeline

diff --git a/.github/workflows/scrape_tournaments.yml b/.github/workflows/scrape_tournaments.yml
--- a/.github/workflows/scrape_tournaments.yml
+++ b/.github/workflows/scrape_tournaments.yml
@@ -27,10 +27,15 @@ jobs:
     - name: Run scraper
       id: scrape
       run: |
-        if python scrape_tournaments.py; then
+        python scrape_tournaments.py
+        exit_code=$?
+        if [ $exit_code -eq 1 ]; then
           echo "new_tournaments=true" >> $GITHUB_OUTPUT
-        else
+        elif [ $exit_code -eq 0 ]; then
           echo "new_tournaments=false" >> $GITHUB_OUTPUT
+        else
+          echo "Script failed with exit code $exit_code"
+          exit $exit_code
         fi
     
     - name: Commit and push if changed
@@ -55,7 +60,7 @@ jobs:
           
           Voici les détails des nouveaux tournois :
           
-          $(cat new_tournaments.csv)
+          $(cat csv/new_tournaments.csv)
         to: damsvdf@yahoo.fr
         from: ${{ secrets.EMAIL_USERNAME }}
         content_type: text/plain 
